HousingForce/src/objects/Housing__c.object
<CustomObject>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Housing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Housing__c</fullName>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Assignment</label>
    <nameField>
        <label>Housing Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HousingForce/src/objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of scheduled service Appointment</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Service Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/classes/ServiceTriggerTest.cls
@isTest
public class ServiceTriggerTest
{
	@TestSetup static void loadData()
    {
        list<Contact> testContact = TestFactory.MuiltContact(false);
        System.assert(testContact.size()>0);
        list<Housing__c> TestHousing = new list<Housing__c>();
        TestHousing.add(TestFactory.singleHousing(false,testContact.size()));
        System.assert(testHousing.size() > 0);
        insert testContact;
        insert TestHousing;
        list<Housing__c> housingIDS = [SELECT ID FROM HOUSING__c];
        list<Contact> contactIds = [SELECT ID FROM CONTACT];
        list<Housing_Assignment__c> newHA = TestFactory.HASingleHousing(Contactids.size(),false,housingIDS[0],ContactIDS);
        System.assert(newHa.size() > 0, 'This doesnt have anything in here');
      //this might not work still 
        insert newHA;

    }	
 /**************************************************************************
 * 	Purpose: To test queryForContacts
 * 	Author:	 Steven Zhao
 * 	Created Date:	4/25/19
 * 	Last Modifyied Author: Steven Zhao
 *  Last Modifyied Date: 4/25/19
 * 	Description: Testing check (0-false/1-true)
 * 					-Postive: 1
 * 					-negative: 1
 * 					-single case: 1
 * 					-Bulk:1
 * 					-restricted user: 0
 *************************************************************************/ 
 @isTest static void ServiceTriggers()
 {
     list<id> HAids = GeneralHelpers.returnIds([SELECT ID FROM HOUSING__C]);
     Test.startTest();
     List<Service_Appointment__c> serviceInsert = TestFactory.MuiltSAcaseforonehousing(false,HAids[0]);
     insert serviceInsert;
     list<Service_Appointment__C> testService = [SELECT ID,Date__c FROM Service_Appointment__c];
     System.assertEquals(20,testService.size(),'pos test fails');
            
     list<Service_Appointment__C> updatelist = new list<Service_Appointment__c>();
     for(Service_Appointment__C SA : testService)
     {
         SA.Date__c = Date.today() +1;
         updatelist.add(SA);
     }
	 try
     {
     	update updatelist;
     }
     catch(DmlException	e)
     {
         System.assert(false,'update is suppose to update');
     }
     Test.stopTest();
     
 }
}