HousingForce/src/objects/Housing__c.object
<CustomObject>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Cleaning_Reason__c</fullName>
        <label>Cleaning Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Single Time</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of scheduled service Appointment</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <description>Grabs the day of the week</description>
        <formula>WEEKDAY(Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DayOfWeek</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Reason__c</fullName>
        <label>Maintenance Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Interval__c</fullName>
        <description>How often cleaning the apartment, (how often housing is cleaned)</description>
        <label>Service Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>The time of the scheduled service</description>
        <label>Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Type_of_Service__c</fullName>
        <label>Type of Service</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cleaning</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Service Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/classes/ServiceController.cls
public class ServiceController {
    // Property to retrieve Service_Appointment__c
    public Service_Appointment__c services{
        get{
            if(services == null){
                this.services = new Service_Appointment__c();
            }
            return services;
        }
        set;
    }
    // Property for a new List of Service Appointments
    public List<Service_Appointment__c> newServList {
        get{
            if(newServList == null){
                newServList = new List<Service_Appointment__c>();
            }
            return newServList;
        }
        set;
    }
    // Property to get a list of most recent services
    public List<Service_Appointment__c> serviceList{
        get{
            if(serviceList == null){
                Integer mnth = System.Today().Month();
                Integer yr = System.Today().Year();
                serviceList = new List<Service_Appointment__c>();
                for(Service_Appointment__c sa : [SELECT Id, DayOfWeek__c, Cleaning_Reason__c, Maintenance_Reason__c, Service_Interval__c, Type_Of_Service__c, Company_Name__c, Date__c, Housing__c, Name, Time__c
                                                 FROM Service_Appointment__c 
                                                 WHERE CALENDAR_MONTH(Date__c) = :mnth AND CALENDAR_YEAR(Date__c) = :yr 
                                                 ORDER BY Date__c 
                                                 LIMIT 15]){                    
                                                     serviceList.add(sa);
                                                 }                
            }
            return serviceList;
        }
        set;
    }
    // Method to save
    public PageReference save(){
		this.newServList.add(this.services);
        return null;
    }
    // Method to cancel
    public PageReference cancel(){
        return null;
    }
    // Property to for bringing in the most recent service
    public List<Service_Appointment__c> upcomingService{
        get{
            if(upcomingService == null){
                Integer mnth = System.Today().Month();
                Integer yr = System.Today().Year();
                upcomingService = new List<Service_Appointment__c>();
                for(Service_Appointment__c us : [SELECT Id, Cleaning_Reason__c, Maintenance_Reason__c, Service_Interval__c, Type_Of_Service__c, Company_Name__c, Date__c, Housing__c, Name, Time__c 
                                                 FROM Service_Appointment__c 
                                                 WHERE CALENDAR_MONTH(Date__c) = :mnth AND CALENDAR_YEAR(Date__c) = :yr 
                                                 ORDER BY Date__c 
                                                 LIMIT 1]){                    
                                                     upcomingService.add(us);
                                                 }                
            }
            return upcomingService;
        }
        set;
    }
    // Property to get picklist values for Type_Of_Service__c
    public List<SelectOption> serviceType{
        get{
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Service_Appointment__c.Type_Of_Service__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            return options;
        }
    }
    // Property to get picklist values for Cleaning_Reason__c
    public List<SelectOption> cleaningOption{
        get{
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Service_Appointment__c.Cleaning_Reason__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            return options;
        }
    }
    // Property to get picklist values for Maintenance_Reason__c
    public List<SelectOption> maintenanceOption{
        get{
            List<SelectOption> options = new List<SelectOption>();
            Schema.DescribeFieldResult fieldResult = Service_Appointment__c.Maintenance_Reason__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
            for( Schema.PicklistEntry f : ple)
                options.add(new SelectOption(f.getLabel(), f.getValue()));
            return options;
        }
    }
}