HousingForce/src/objects/Housing__c.object
<CustomObject>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Housing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Assignment</label>
    <nameField>
        <label>Housing Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HousingForce/src/objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <description>Grabs the day of the week</description>
        <formula>WEEKDAY(Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DayOfWeek</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Interval__c</fullName>
        <description>How often cleaning the apartment, (how often housing is cleaned)</description>
        <label>Service Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>The time of the scheduled service</description>
        <label>Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Type_of_Service__c</fullName>
        <label>Type of Service</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cleaning</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Service Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/classes/ServiceAppointmentEmail.cls
/**************************************************************************
 * 	Purpose: A class to hold all of the methods for the ServiceAppointmentEnail
 * 	Author:	 Steven Zhao
 * 	Created Date:	 4/23/19
 * 	Last Modifyied Author: Steven Zhao
 *  Last Modifyied Date: 4/23/19
 * 	Description:	
 *************************************************************************/ 
public class ServiceAppointmentEmail 
{
/**************************************************************************
 * 	Purpose: return a map of contactid and serivce.
 * 	Author:	 Steven Zhao
 * 	Created Date:	 4/23/19
 * 	Last Modifyied Author: Steven Zhao
 *  Last Modifyied Date: 4/23/19
 * 	Description:	
 *************************************************************************/ 
	public static Map<id,String> returnServiceAppointment(list<ID> newlist)
    {
       Map<id,String> ServiceList = new Map<id,string>();
       For(HOUSING__C tempH: [SELECT  (SELECT 	Service_Interval__c	,DayOfWeek__c,time__C FROM Service_Appointments__R 
                                       WHERE Type_of_Service__c = :OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE[0].getLabel()
                                       AND 	Service_Interval__c !=0),
                              (SELECT CONTACT__C FROM HOUSING_ASSIGNMENTS__R WHERE CONTACT__C IN :NEWLIST)
                              FROM HOUSING__C 
                              WHERE ID IN (SELECT  HOUSING__C FROM HOUSING_ASSIGNMENT__C WHERE CONTACT__C IN :NEWLIST ) ])
       {
           For(Service_Appointment__c tempSAC: tempH.Service_Appointments__r)
           {
               FOR(Housing_Assignment__C tempHA : tempH.housing_assignments__r)
               {
                   if(ServiceList.get(tempHA.contact__C)==null)
                   		ServiceList.put(tempHA.contact__C,(' day : '+GeneralHelpers.returnDayofWeek(integer.valueof(tempSAC.DayOfWeek__c))+' every '+GeneralHelpers.returnWeekANDdays(integer.valueOF(tempSAC.Service_Interval__c))+ ' Time: ' + tempSAC.time__C));
               }
             	
           }
       }
        return ServiceList;
    }

    

}