HousingForce/src/objects/Housing__c.object
<CustomObject>
    <fields>
        <fullName>Group_Designation__c</fullName>
        <label>Group Designation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Men only</fullName>
                </value>
                <value>
                    <fullName>Women only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Cleaning_Reason__c</fullName>
        <label>Cleaning Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Single Time</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Reason__c</fullName>
        <label>Maintenance Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Service__c</fullName>
        <label>Type of Service</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cleaning</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Service Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/classes/OrgContants.cls
/**************************************************************************
 * 	Purpose: Contant Values that the org uses
 * 	Author:	 Steven Zhao
 * 	Created Date:	
 * 	Last Modifyied Author:
 *  Last Modifyied Date:
 * 	Description:	Mostly just picklistvalues
 *************************************************************************/ 
public class OrgContants
{
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_EmloyeeStatus = Contact.Employee_Status__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_GENDER = Contact.Gender__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_HOUSING_GENDER = Housing__C.Group_Designation__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_HOUSING_ASSIGNMENT = Contact.Housing_Status__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_TASK_SUBJECT = Task.Subject.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_TASK_STATUS = Task.STATUS.getDescribe().getpicklistValues();
	public static Final list<schema.PicklistEntry>  PICKLISTVALUE_TASK_PRIORITY = Task.PRIORITY.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>  PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE = Service_Appointment__c.Type_of_Service__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>	PICKLISTVALUE_SERVICE_APPOINTMENT_CLEANING_REASON = Service_Appointment__c.Cleaning_Reason__c.getDescribe().getpicklistValues();
    public static Final list<schema.PicklistEntry>	PICKLISTVALUE_SERVICE_APPOINTMENT_MAINTENANCE_REASON = Service_Appointment__c.Maintenance_Reason__c.getDescribe().getpicklistValues();

}