HousingForce/src/objects/Housing__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Housing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Assignment</label>
    <nameField>
        <label>Housing Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HousingForce/src/classes/ContactTriggerHelperHelperMethods.cls
public class ContactTriggerHelperHelperMethods 
{
 /**************************************************************************
 * 	Purpose: Creates the Body for the email.
 * 	Author:	 Steven Zhao
 * 	Created Date:	4/19/19
 * 	Last Modifyied Author:Steven Zhao
 *  Last Modifyied Date:4/19/19
 * 	Description:	This is a body text for the new howing email
 *************************************************************************/ 
    public static String NewHousingApprovalMessage(String firstName, String lastName,String address,String HousingEmail)
    {
        String Body = 'Dear '+firstName +' '+lastName
           +'\n You have been approved for housing and'+
            ' your new housing is at '+address+'. \n'
            +'Contact the housing department at '
            +housingEmail+',If you have any further '
            +'questions.';

        return Body;
    }
/**************************************************************************
 * 	Purpose: Query for Address
 * 	Author:	 Steven Zhao
 * 	Created Date:	4/19/19
 * 	Last Modifyied Author:Steven Zhao
 *  Last Modifyied Date:4/19/19
 * 	Description:	this return a map of an contact id and the address that is related to it.
 *************************************************************************/ 
    public static Map<id,String> queryAddress(list<id> contactIds)
    {
        Map<id,String> address = new Map<id,String>();
        if(contactIds.size()>0 && contactIds != null )
        {
            For(Housing_Assignment__C tempHA: [SELECT Contact__c,Housing__r.Address__c FROM Housing_Assignment__C])
            {
                For(Id tempId: contactIds)
                {
                    if(tempHA.Contact__c == tempId)
                    {
                       address.put(tempId,String.valueOf(tempHA.Housing__r.Address__c));
                    }
                }
            }
        }
        return address;
    }    

}