HousingForce/src/objects/Housing__c.object
<CustomObject>
    <fields>
        <fullName>Current_Occupants__c</fullName>
        <label>Current Occupants</label>
        <summaryForeignKey>Housing_Assignment__c.Housing__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Housing</label>
    <nameField>
        <label>Housing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/objects/Housing_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Housing Assignments</relationshipLabel>
        <relationshipName>Housing_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Assignment</label>
    <nameField>
        <label>Housing Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HousingForce/src/objects/Service_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Cleaning_Reason__c</fullName>
        <label>Cleaning Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Temporary</fullName>
                </value>
                <value>
                    <fullName>Single Time</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of scheduled service Appointment</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <description>Grabs the day of the week</description>
        <formula>WEEKDAY(Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DayOfWeek</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Housing__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Housing</label>
        <referenceTo>Housing__c</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Reason__c</fullName>
        <label>Maintenance Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type_of_Service__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Interval__c</fullName>
        <description>How often cleaning the apartment, (how often housing is cleaned)</description>
        <label>Service Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <description>The time of the scheduled service</description>
        <label>Time</label>
        <required>true</required>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Type_of_Service__c</fullName>
        <label>Type of Service</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cleaning</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Appointment</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>Service Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

HousingForce/src/classes/ServiceAppointmentTriggerHelper.cls
public WITH SHARING class ServiceAppointmentTriggerHelper 
{
    /**************************************************************************
* 	Purpose:  to check the type of Service being created, checking if its either cleaning or maintaince
* 	Author:	 Steven Zhao
* 	Created Date:	4/24/19
* 	Last Modifyied Author: Steven Zhao
*   Last Modifyied Date:
* 	Description:	
*************************************************************************/	
    public static void checkServiceForTriggerInsert(list<Service_Appointment__C> newlist)
    {	//check if cleaning or maintenance
        
        if(newlist != null && newlist.size() > 0)
        {
            List<id> CleaningHousingIds = new list<id>();
            List<id> MaintenanceHousingIds = new list<id>();
            for(Service_Appointment__C tempSAC : newlist)
            {
                if(tempSAC.Type_of_Service__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE[0].getLabel())
                { 
                    CleaningHousingIds.add(tempSAC.Housing__c);
                }
                else if(tempSAC.Type_of_Service__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE[1].getLabel())
                {
                    MaintenanceHousingIds.add(TempSAC.Housing__c);
                }
            }
            
            //otherwise if there are people email them
            if(CleaningHousingIds != null && CleaningHousingIds.size() > 0)
            { //check if current house has people AND QUERY FOR HOUSING WITH PEOPLE
                map<id,list<String>> contactEmailsForCleaning = queryForContacts(CleaningHousingIds);
                String subject = '<no-reply> new Cleaning Appointment';
                CreateAndSendEmail(CleaningHousingIds,subject,newlist,contactEmailsForCleaning,0);	
            }
            
            if(MaintenanceHousingIds != null && MaintenanceHousingIds.Size() > 0)
            {//checks for the current contact email in the house and sends an email to them
                map<id,list<String>> contactEmailsForMaintenance = queryForContacts(MaintenanceHousingIds);
                String subject = '<no-reply new Maintenance Appointment>';
                CreateAndSendEmail(MaintenanceHousingIds,subject,newlist,contactEmailsForMaintenance,1);
            }
        }       
    }
    
/**************************************************************************
* 	Purpose:Check for update change and if the change is related to a new day
* 	Author:	 Steven Zhao	
* 	Created Date:	4/23/19
* 	Last Modifyied Author: Steven Zhao
*  Last Modifyied Date: 4/23/19
* 	Description:	 this returns a map<id,list<string>> to email the user to the related service appointments (cleaning or maintaince)
*************************************************************************/
    public static void checkServiceForTriggerUpdate(list<Service_Appointment__C> newlist, Map<id,Service_Appointment__C> oldMap)
    {
        List<id> CleaningHousingIds = new list<id>();
        List<id> MaintenanceHousingIds = new list<id>();
        for(Service_Appointment__c tempSAC : newlist)
        {
            if(oldMap.get(tempSAC.Id) != null)
            {	Service_Appointment__c tempSA= oldMap.get(tempSAC.Id);
             if((GeneralHelpers.returnDayofWeek(Integer.valueof(tempSAC.DayOfWeek__c)) != GeneralHelpers.returnDayofWeek(Integer.valueof(tempSA.DayOfWeek__c))) && 
                (tempSAC.Cleaning_Reason__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_CLEANING_REASON[0].getLabel()
                 ||tempSAC.Maintenance_Reason__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_MAINTENANCE_REASON[0].getLabel()))
             {
                 if(tempSAC.Type_of_Service__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE[0].getLabel())
                 { 
                     CleaningHousingIds.add(tempSAC.Housing__c);
                 }
                 else if(tempSAC.Type_of_Service__c == OrgContants.PICKLISTVALUE_SERVICE_APPOINTMENT_TYPEOFSERVICE[1].getLabel())
                 {
                     MaintenanceHousingIds.add(TempSAC.Housing__c);
                 }
                 
             }
            }
            //otherwise if there are people email them
            if(CleaningHousingIds != null && CleaningHousingIds.size() > 0)
            { //check if current house has people AND QUERY FOR HOUSING WITH PEOPLE
                map<id,list<String>> contactEmailsForCleaning = queryForContacts(CleaningHousingIds);
                String subject = '<no-reply> new Cleaning Appointment';
                CreateAndSendEmail(CleaningHousingIds,subject,newlist,contactEmailsForCleaning,0);	
            }
            
            if(MaintenanceHousingIds != null && MaintenanceHousingIds.Size() > 0)
            {//checks for the current contact email in the house and sends an email to them
                map<id,list<String>> contactEmailsForMaintenance = queryForContacts(MaintenanceHousingIds);
                String subject = '<no-reply new Maintenance Appointment>';
                CreateAndSendEmail(MaintenanceHousingIds,subject,newlist,contactEmailsForMaintenance,1);
            }
        }
    }
    /**************************************************************************
* 	Purpose: To return the email of the contacts related to the housing 
* 	Author:	 Steven Zhao	
* 	Created Date:	4/23/19
* 	Last Modifyied Author: Steven Zhao
*  Last Modifyied Date: 4/23/19
* 	Description:	 this returns a map<id,list<string>> to email the user to the related service appointments (cleaning or maintaince)
*************************************************************************/
    public static map<id,list<String>> queryForContacts(list<id> newIDlist)
    {
        Map<id,list<String>> contactEmails = new Map<id,list<String>>();
        for(housing__c tempH : [SELECT Id, (SELECT CONTACT__r.Email FROM HOUSING_ASSIGNMENTS__R) from housing__C where CURRENT_OCCUPANTS__C != 0 AND ID IN :newIDlist])
        {
            for(Id tempID : newIDlist)
            {
                if(tempId == tempH.id)
                {
                    list<String> emailList = new list<String>();
                    for(Housing_Assignment__c tempHA : tempH.Housing_Assignments__r)
                    {
                        emailList.add(tempHA.Contact__r.Email);
                    }
                    if(contactEmails.get(tempId) == null)
                        contactEmails.put(TempH.id,emailList);
                }
            }
        }
        return contactEmails;
    }	
    /**************************************************************************
* 	Purpose:  creates emails and send the email
* 	Author:	 Steven Zhao
* 	Created Date:	4/24/19
* 	Last Modifyied Author: Steven Zhao
*  Last Modifyied Date: 4/24/19
* 	Description:	
*************************************************************************/	
    public static void CreateAndSendEmail(list<id> housingid, string subject ,list<Service_Appointment__c> newlist,map<id,list<string>> contactEmail,integer serviceType)
    {	
        for(Service_Appointment__c tempSAC:newlist)
        {
            for(id tempId:housingid)
            {
                if(tempId == tempSAC.Housing__c)
                {//Service_Interval__c
                    String tBody = textBody(serviceType,integer.valueOf(tempSAC.Service_Interval__c),integer.valueOf(tempSAC.DayOfWeek__c),tempSAC.Date__C,tempSAC.Time__C);
                    list<Messaging.SingleEmailMessage> newEmail = OutBoundEmail.Create_Email(contactEmail.get(tempId),subject,tBody);
                    System.debug(newEmail);
                    Messaging.sendEmail(newEmail);
                }
            }
        }
    }
    /**************************************************************************
* 	Purpose:  The body for the housing text body
* 	Author:	 Steven Zhao
* 	Created Date:	4/24/19
* 	Last Modifyied Author: Steven Zhao
*  Last Modifyied Date: 4/24/19
* 	Description:	
*************************************************************************/	
    public static string textBody( integer Service,integer numberDays, integer dayofWeek, date serviceDate, time serviceTime)
    {
        //if service is 0 it means cleaning otherwise if its 1 it means maintance
        if(Service == 0 )
        {
            if(numberDays ==null || numberDays ==0)
            {
                return 'Cleaning will be on ' +serviceDate +' at '+serviceTime;
            }
            else 
                return 'Cleaning will be on ' +GeneralHelpers.returnDayofWeek(dayofWeek)+' every '+GeneralHelpers.returnWeekANDdays(numberDays)+' Starting: '+serviceDate;
        }
        else if (Service == 1)
        {
            if(numberDays ==null || numberDays ==0)
            {
                return 'Maintaince will be on ' +serviceDate +' at '+serviceTime;
            }
            else 
                return 'Maintaince will be on ' +GeneralHelpers.returnDayofWeek(dayofWeek)+' every '+GeneralHelpers.returnWeekANDdays(numberDays)+'Starting: '+serviceDate;
        }
        else
            return null;
        
        
    }
    
}